## **Creating Arrays** ##

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from 'C:\\ProgramData\\anaconda3\\envs\\ml-zoomcamp\\Lib\\site-packages\\numpy\\__init__.py'>

In [4]:
#Creating Arrays
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [6]:
a[2]

3

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
array_from_list = np.array(a)
array_from_list

array([ 1,  2, 10,  5,  7, 12])

In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n            

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
n[:, 0]

array([1, 4, 7])

In [17]:
np.random.seed(2)
np.random.rand(5, 2)


array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [18]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [20]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [31]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [32]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations ##

In [33]:
a

array([0, 1, 2, 3, 4])

In [34]:
a >= 2

array([False, False,  True,  True,  True])

In [35]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [36]:
a > b

array([False, False,  True,  True,  True])

In [37]:
a[a > b]

array([2, 3, 4])

## Summarizing operations ##

In [38]:
a

array([0, 1, 2, 3, 4])

In [40]:
a.sum()

10

In [42]:
a.std()

1.4142135623730951

In [43]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
n.max()

9

## **Pandas** ##

In [49]:
import pandas as pd

## **Data Frames** ##

In [51]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [56]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [70]:
df[['Make', 'Model', 'Engine Cylinders']]

Make     Model  Engine Cylinders
0   Nissan    Stanza                 4
1  Hyundai    Sonata                 4
2    Lotus     Elise                 4
3      GMC    Acadia                 4
4   Nissan  Frontier                 6

In [73]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [75]:
df.loc[[1,3]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
1         Sedan  27150  
3       4dr SUV  34450