## Homework ##

In [16]:
import pandas as pd

In [67]:
import numpy as np

In [17]:
pd.__version__

'2.2.2'

In [18]:
df = pd.read_csv("C:/Users/Edan/Downloads/laptops.csv")
print(df)

                                                 Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RA

In [19]:
df.count(axis=0)

Laptop          2160
Status          2160
Brand           2160
Model           2160
CPU             2160
RAM             2160
Storage         2160
Storage type    2118
GPU              789
Screen          2156
Touch           2160
Final Price     2160
dtype: int64

There are 12 records in the dataset

In [20]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

There are 2160 laptop brands

In [21]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

2 columns have missing values
Storage type and GPU

In [22]:
df.loc[df['Final Price'].idxmax()]

Laptop          MSI Raider GE78HX 13VH-065ES Intel Core i9-139...
Status                                                        New
Brand                                                         MSI
Model                                                      Raider
CPU                                                 Intel Core i9
RAM                                                            32
Storage                                                      2000
Storage type                                                  SSD
GPU                                                      RTX 4080
Screen                                                       17.0
Touch                                                          No
Final Price                                               7150.47
Name: 1099, dtype: object

In [23]:
df.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [24]:
df['Screen'].median()

15.6

In [25]:
df.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [28]:
df.groupby('Brand')['Final Price'].agg(['min', 'mean', 'max'])
#data.groupby('Brand')['Final Price'].agg(['min', 'mean', 'max'])

min         mean      max
Brand                                          
Acer               264.14  1001.285766  3691.00
Alurin             239.00   484.701379   869.00
Apple              299.00  1578.227672  3849.00
Asus               239.25  1269.380699  5758.14
Deep Gaming       1334.00  1505.377500  1639.01
Dell               379.00  1153.839881  3936.00
Denver             329.95   329.950000   329.95
Dynabook Toshiba   397.29   999.197895  1805.01
Gigabyte           799.00  1698.488958  3799.00
HP                 210.14   952.628478  5368.77
Innjoo             251.40   347.888333   431.38
Jetwing            469.27   469.270000   469.27
LG                 609.04  1730.028438  2399.00
Lenovo             239.00  1087.723880  5018.14
MSI                444.19  1913.451006  7150.47
Medion             246.89   905.331875  3799.00
Microsoft          599.01  1595.543247  3747.91
Millenium         1640.98  1976.845000  2312.71
PcCom             1049.00  1606.762917  1949.90
Primux             208.99   339.618750   599.41
Prixton            246.95   292.280000   329.95
Razer             1232.74  3265.701622  4999.01
Realme             999.00   999.000000   999.00
Samsung            365.90  1595.511364  3699.01
Thomson            201.05   316.860000   436.56
Toshiba            799.00   799.000000   799.00
Vant               632.00  1047.455455  1217.01

In [32]:
df[df.Brand == 'Dell']['Final Price'].max()
#data[data.Brand == 'Dell']['Final Price'].max()

3936.0

In [41]:
median = df['Screen'].median()
median

15.6

In [42]:
mode = df['Screen'].mode()[0]
mode

15.6

In [44]:
df['Screen'].fillna(mode).median()

15.6

In [48]:
Innjoo = df[df.Brand == 'Innjoo']
Innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [50]:
Innjoo = Innjoo[['RAM', 'Storage', 'Screen']]
Innjoo

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [59]:
X = Innjoo.values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [76]:
XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [74]:
y= [1100, 1300, 800, 900, 1000, 1100]
y

[1100, 1300, 800, 900, 1000, 1100]

In [78]:
w = (XTX_inv @ X.T) @ y
w

array([45.58076606,  0.42783519, 45.29127938])

In [79]:
sum(w)

91.29988062995815